name: MyItemLibrary
version: '${project.version}'
main: org.cakedek.myitemlibrary.MyItemLibrary
api-version: '1.20'
commands:
  my-library-reload:
    description: Reloads the MyItemLibrary plugin
    usage: /<command>
    permission: my_item_library.admin.reload
    hidden: true
  my-library:
    description: Opens the library GUI
    usage: /<command>